/* Pipeline para corroborar la versión de node y ejecutar el llamado a una API */
pipeline {
    agent any
    stages {
        stage('environment') {
            steps {
                sh 'node --version'
                sh 'npm --version'
            }
        }

        stage('run') {
            steps {
                sh 'cd nodejs/'
                sh 'node src/main.js'
            }
        }
    }

    post {
        success {
            echo '¡Pipeline ejecutada con éxito!'
        }
        failure {
            echo '¡Error al ejecutar Pipeline!'
        }
    }

}
